
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.text.NumberFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Elin
 */
public class GestionPedidos extends javax.swing.JFrame {

    private static final String[] Estatus = {"Disponible para recolección", "Artículos no disponibles",
        "En proceso" , "Entregado"};
    
    private void cargarCategorias(javax.swing.JComboBox<String> lista){
        lista.removeAllItems();
        
        for(String Estatus : Estatus){
            lista.addItem(Estatus);
        }
        
        lista.setSelectedItem("En proceso");
    }
    
    private CRUDpedidos crud;
    
    public GestionPedidos() {
        initComponents();
        crud = new CRUDpedidos();
        
        JFormattedTextField txt = ((JSpinner.NumberEditor) jSpinner1.getEditor()).getTextField();
        NumberFormatter formatter = (NumberFormatter) txt.getFormatter();
        formatter.setAllowsInvalid(false);
        
        cargarCategorias(boxEstatus);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpGPedidos = new javax.swing.JPanel();
        jlabelUsuario4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boxEstatus = new javax.swing.JComboBox<>();
        btnRegresar2 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpGPedidos.setBackground(new java.awt.Color(204, 204, 204));
        jpGPedidos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelUsuario4.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jlabelUsuario4.setText("Gestión de Pedidos");
        jpGPedidos.add(jlabelUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Actualizar pedido");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jpGPedidos.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 140, -1));

        jButton8.setBackground(new java.awt.Color(197, 245, 245));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setText("Actualizar tabla");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jpGPedidos.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 470, 180, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Pedido", "Departamento", "Fecha", "Artículos solicitados", "Total de artículos", "Estado del pedido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(3);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(3);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        jpGPedidos.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 780, 378));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("ID del pedido:");
        jpGPedidos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 100, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nuevo estatus:");
        jpGPedidos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 110, -1));

        boxEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEstatusActionPerformed(evt);
            }
        });
        jpGPedidos.add(boxEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 140, -1));

        btnRegresar2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRegresar2.setText("Regresar");
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });
        jpGPedidos.add(btnRegresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 110, 30));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100000, 1));
        jpGPedidos.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpGPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpGPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int id = (int)jSpinner1.getValue();
        int estatus = (boxEstatus.getSelectedIndex())+1;
        String botones[] = {"Confirmar", "Cancelar"};
        int decision = JOptionPane.showOptionDialog(null, "Se actualizará el pedido con el ID '" + id + "' al estatus '"+ (String) boxEstatus.getSelectedItem()+"'\n"
                , "Actualización de pedido",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, botones, botones[0]);
        if(decision == 0){
            boolean status = crud.actualizarPedido(id, estatus);
            if(status){
                JOptionPane.showMessageDialog(null, "El pedido se actualizó exitosamente", "Actualización de pedido", JOptionPane.INFORMATION_MESSAGE);
                jSpinner1.setValue(0);
                boxEstatus.setSelectedItem("En proceso");
            }else{
                JOptionPane.showMessageDialog(null, "ERROR: El pedido no fue modificado debido a un error.", "Actualización de pedido", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            return;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        CRUDpedidos pedidoManager = new  CRUDpedidos();
        pedidoManager.mostrarPedidos(jTable2);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
        regresar();
    }//GEN-LAST:event_btnRegresar2ActionPerformed

    private void boxEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxEstatusActionPerformed

    private void regresar(){
        this.setVisible(false);
        this.dispose();
        MenuAdmin MA = new MenuAdmin();
        MA.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEstatus;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jlabelUsuario4;
    private javax.swing.JPanel jpGPedidos;
    // End of variables declaration//GEN-END:variables
}
