/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Elin
 */

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFormattedTextField;
import javax.swing.text.NumberFormatter;

public class AdministracionArticulos extends javax.swing.JFrame {

    private CRUDArticulos crud;
    
    private static final String[] Categorias = {"Papel", "Escritura", "Organización" , "Electrónicos", "Empaque"};
    
    private void cargarCategorias(javax.swing.JComboBox<String> lista){
        lista.removeAllItems();
        
        for(String Categoria : Categorias){
            lista.addItem(Categoria);
        }
        
        lista.setSelectedItem("Papel");
    }
    /**
     * Creates new form AdministracionArticulos
     */
    public AdministracionArticulos() {
        initComponents();
        cargarCategorias(boxCategoriasRegistro);
        cargarCategorias(boxCategoriasActualizacion);
        crud = new CRUDArticulos();
        
        JFormattedTextField txt1 = ((JSpinner.NumberEditor) spinID.getEditor()).getTextField();
        JFormattedTextField txt2 = ((JSpinner.NumberEditor) spinCantidad.getEditor()).getTextField();
        NumberFormatter formatter1 = (NumberFormatter) txt1.getFormatter();
        NumberFormatter formatter2 = (NumberFormatter) txt2.getFormatter();
        formatter1.setAllowsInvalid(false);
        formatter2.setAllowsInvalid(false);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtArticulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        boxCategoriasRegistro = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtNombreConsulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulosConsulta = new javax.swing.JTable();
        btnBuscarConsulta = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();
        btnRegresar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtNombreActualizacion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        boxCategoriasActualizacion = new javax.swing.JComboBox<>();
        spinID = new javax.swing.JSpinner();
        btnRegresar2 = new javax.swing.JButton();
        spinCantidad = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblArticulosEliminar = new javax.swing.JTable();
        btnBuscarNombreEliminar = new javax.swing.JButton();
        txtNombreEliminar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnRegresar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Merks and Spen");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 560, 31));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de artículos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 548, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 106, 493, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre de artículo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 143, 191, -1));

        txtArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArticuloActionPerformed(evt);
            }
        });
        jPanel1.add(txtArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 143, 230, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Categoría:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 183, 191, -1));

        btnAgregar.setBackground(new java.awt.Color(102, 255, 102));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar artículo");
        btnAgregar.setMaximumSize(new java.awt.Dimension(142, 24));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 493, 40));

        boxCategoriasRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(boxCategoriasRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 183, 180, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("*Se generará el registro con una cantidad de 0");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 493, -1));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 110, -1));

        jTabbedPane4.addTab("Registro", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Merks and Spen");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 560, 31));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Consulta de artículos");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 548, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 106, 493, -1));

        txtNombreConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombreConsulta.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreConsultaActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 161, -1));

        tblArticulosConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Artículo", "Cantidad", "Categoría"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblArticulosConsulta);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 127, 493, 140));

        btnBuscarConsulta.setBackground(new java.awt.Color(153, 153, 153));
        btnBuscarConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarConsulta.setText("Buscar por nombre");
        btnBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConsultaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        btnMostrarTodos.setBackground(new java.awt.Color(153, 153, 255));
        btnMostrarTodos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMostrarTodos.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarTodos.setText("Mostrar todos");
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });
        jPanel2.add(btnMostrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        btnRegresar1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRegresar1.setText("Regresar");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 110, -1));

        jTabbedPane4.addTab("Consulta", jPanel2);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Merks and Spen");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 560, 31));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Actualización de artículos");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 548, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 106, 493, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Nombre de artículo:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 191, -1));

        txtNombreActualizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActualizacionActionPerformed(evt);
            }
        });
        jPanel4.add(txtNombreActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 230, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Cantidad:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 191, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 204, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar artículo");
        btnActualizar.setMaximumSize(new java.awt.Dimension(142, 24));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 493, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("ID:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 191, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Categoría:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 191, -1));

        boxCategoriasActualizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(boxCategoriasActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 230, -1));

        spinID.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100000, 1));
        jPanel4.add(spinID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 230, -1));

        btnRegresar2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRegresar2.setText("Regresar");
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 110, -1));

        spinCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100000, 1));
        jPanel4.add(spinCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 230, -1));

        jTabbedPane4.addTab("Actualización", jPanel4);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Merks and Spen");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 560, 31));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Eliminación de artículos");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 548, -1));

        tblArticulosEliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Artículo", "Cantidad", "Categoría"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblArticulosEliminar);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 493, 140));

        btnBuscarNombreEliminar.setBackground(new java.awt.Color(153, 153, 153));
        btnBuscarNombreEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarNombreEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarNombreEliminar.setText("Buscar por nombre");
        btnBuscarNombreEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarNombreEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 135, -1, -1));

        txtNombreEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombreEliminar.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreEliminar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombreEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 135, 190, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar artículo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 135, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 106, 493, -1));

        btnRegresar3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRegresar3.setText("Regresar");
        btnRegresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegresar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 110, -1));

        jTabbedPane4.addTab("Eliminación", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArticuloActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtArticulo.getText();
        String categoria = (String)boxCategoriasRegistro.getSelectedItem();

        if(nombre.isEmpty()){
            JOptionPane.showMessageDialog(null, "ERROR: Todos los campos son obligatorios.", "Registro de departamento", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean status = crud.crearArticulo(nombre, categoria);

        if(status){
            JOptionPane.showMessageDialog(null, "El artículo se guardó exitosamente", "Registro de artículo", JOptionPane.INFORMATION_MESSAGE);
            txtArticulo.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "ERROR: El artículo no fue guardado debido a un error.", "Registro de artículo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreConsultaActionPerformed

    private void btnBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConsultaActionPerformed
        String nombre = txtNombreConsulta.getText();
        if(nombre.isEmpty()){
            JOptionPane.showMessageDialog(null, "ERROR: Es necesario ingresar un ID para generar una consulta." , "Consulta de artículo", JOptionPane.QUESTION_MESSAGE);
            return;
        }
        try{
            ResultSet consulta = crud.obtenerArticuloNombre(nombre);
            DefaultTableModel modelo = (DefaultTableModel)tblArticulosConsulta.getModel();
            modelo.setRowCount(0);
            if(consulta.next()){
                modelo.addRow(new Object[]{consulta.getInt("id"), consulta.getString("nombre"), consulta.getInt("cantidad"), consulta.getString("categoria")});
            }
            txtNombreConsulta.setText("");
        }catch(SQLException e){
            System.out.println("Error al intentar llenar la tabla:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarConsultaActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        ResultSet consultaTodos = crud.obtenerArticulos();
        DefaultTableModel modelo = (DefaultTableModel)tblArticulosConsulta.getModel();
        modelo.setRowCount(0);

        try{
            while(consultaTodos.next()){
                modelo.addRow(new Object[]{consultaTodos.getInt("id"), consultaTodos.getString("nombre"), consultaTodos.getInt("cantidad"), consultaTodos.getString("categoria")});
            }
        }catch(SQLException e){
            System.out.println("Error al intentar llenar la tabla:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void txtNombreActualizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActualizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActualizacionActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int id = (int)spinID.getValue();
        String nombre = txtNombreActualizacion.getText();
        int cantidad = (int)spinCantidad.getValue();
        String categoria = (String)boxCategoriasActualizacion.getSelectedItem();

        if(nombre.isEmpty()){
            JOptionPane.showMessageDialog(null, "ERROR: Todos los campos son obligatorios.", "Actualización de artículo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String botones[] = {"Sí", "No"};
        int decision = JOptionPane.showOptionDialog(null, "Se actualizará el artículo con el ID '" + id + "' con los siguientes datos:\n"
            + "Nombre: " + nombre
            + "\nCantidad: " + cantidad
            + "\nCategoría: " + categoria,
            "Actualización de usuario", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, botones, botones[0]);
        if(decision == 0){
            boolean status = crud.actualizarArticulo(id, nombre, cantidad, categoria);
            if(status){
                JOptionPane.showMessageDialog(null, "El artículo se actualizó exitosamente", "Actualización de artículo", JOptionPane.INFORMATION_MESSAGE);
                spinID.setValue(0);
                txtNombreActualizacion.setText("");
                spinCantidad.setValue(0);
            }else{
                JOptionPane.showMessageDialog(null, "ERROR: El usuario no fue guardado debido a un error.", "Actualización de departamento", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            return;
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarNombreEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreEliminarActionPerformed
        String nombre = txtNombreEliminar.getText();
        if(nombre.isEmpty()){
            JOptionPane.showMessageDialog(null, "ERROR: Es necesario ingresar un nombre para generar una consulta." , "Consulta de artículo", JOptionPane.QUESTION_MESSAGE);
            return;
        }
        try{
            ResultSet consulta = crud.obtenerArticuloNombre(nombre);
            DefaultTableModel modelo = (DefaultTableModel)tblArticulosEliminar.getModel();
            modelo.setRowCount(0);
            if(consulta.next()){
                modelo.addRow(new Object[]{consulta.getInt("id"), consulta.getString("nombre"), consulta.getInt("cantidad"), consulta.getString("categoria")});
            }
        }catch(SQLException e){
            System.out.println("Error al intentar llenar la tabla:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarNombreEliminarActionPerformed

    private void txtNombreEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEliminarActionPerformed
        
    }//GEN-LAST:event_txtNombreEliminarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String nombre = txtNombreEliminar.getText();
        if(nombre.isEmpty()){
            JOptionPane.showMessageDialog(null, "ERROR: Es necesario ingresar un ID para eliminar un usuario." , "Eliminación de departamento", JOptionPane.QUESTION_MESSAGE);
            return;
        }
        String botones[] = {"Sí", "No"};
        int decision = JOptionPane.showOptionDialog(null, "¿Estás seguro de querer eliminar el artículo '" + nombre + "'?",
            "Eliminación de usuario", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, botones, botones[0]);
        if(decision == 0){
            boolean status = crud.eliminarArticulo(nombre);
            if(status){
                JOptionPane.showMessageDialog(null, "El usuario se eliminó exitosamente", "Eliminación de artículo", JOptionPane.INFORMATION_MESSAGE);
                txtNombreEliminar.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "ERROR: El usuario no fue eliminó debido a un error.", "Eliminación de artículo", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            return;
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        regresar();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        regresar();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
        regresar();
    }//GEN-LAST:event_btnRegresar2ActionPerformed

    private void btnRegresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar3ActionPerformed
        regresar();
    }//GEN-LAST:event_btnRegresar3ActionPerformed

    private void regresar(){
        this.setVisible(false);
        this.dispose();
        MenuAdmin MA = new MenuAdmin();
        MA.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionArticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCategoriasActualizacion;
    private javax.swing.JComboBox<String> boxCategoriasRegistro;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarConsulta;
    private javax.swing.JButton btnBuscarNombreEliminar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JButton btnRegresar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JSpinner spinCantidad;
    private javax.swing.JSpinner spinID;
    private javax.swing.JTable tblArticulosConsulta;
    private javax.swing.JTable tblArticulosEliminar;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtNombreActualizacion;
    private javax.swing.JTextField txtNombreConsulta;
    private javax.swing.JTextField txtNombreEliminar;
    // End of variables declaration//GEN-END:variables
}
